# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "sd_mod" "bcache" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptroot";
      fsType = "bcachefs";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/5ffdc7ff-c339-4b43-ba5c-9b2a2b315665";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/B0C0-4228";
      fsType = "vfat";
    };

  fileSystems."/mnt/ssd0" =
    { device = "/dev/mapper/cryptssd0";
      fsType = "bcachefs";
    };

  boot.initrd.luks.devices."cryptssd0".device = "/dev/disk/by-uuid/08d49d5b-ff8f-4fce-9caa-fa6b8182784d";

  fileSystems."/mnt/hdd0" =
    { device = "/dev/mapper/crypthdd0";
      fsType = "bcachefs";
    };

  boot.initrd.luks.devices."crypthdd0".device = "/dev/disk/by-uuid/27fa07de-7cd5-473f-9254-ed1553030d36";

  fileSystems."/mnt/hdd1" =
    { device = "/dev/mapper/crypthdd1";
      fsType = "bcachefs";
    };

  boot.initrd.luks.devices."crypthdd1".device = "/dev/disk/by-uuid/853889f3-e0c8-4ad2-90a4-9117f6ec2985";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3ec1c76a-a7eb-4b18-a9ff-7424d25cd44b"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
}
