# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d8035775-b361-4278-9c14-4b56db05cac8";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/7e179ba5-0d32-4bbf-9226-7713021a18e7";

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/d8035775-b361-4278-9c14-4b56db05cac8";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d8035775-b361-4278-9c14-4b56db05cac8";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0624848c-3709-4302-bda0-ffb52247e8bd";
      fsType = "btrfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/3016-BECE";
      fsType = "vfat";
    };

  fileSystems."/mnt/ssd1" =
    { device = "/dev/disk/by-uuid/d72e67a4-06ab-49ce-97e2-78bd3f3124b2";
      fsType = "btrfs";
      options = [ "subvol=@ssd1" ];
    };

  boot.initrd.luks.devices."cryptssd1".device = "/dev/disk/by-uuid/37e18604-2e99-4122-96b0-8a9d8cc62908";

  fileSystems."/virt/ssd1" =
    { device = "/dev/disk/by-uuid/96bb4954-4b19-4941-9e7f-157d318bdf50";
      fsType = "btrfs";
      options = [ "subvol=@wssd1" ];
    };

  boot.initrd.luks.devices."cryptwssd1".device = "/dev/disk/by-uuid/d5aac138-fccb-4f6c-bf34-36caf5555a1e";

  fileSystems."/mnt/hdd0" =
    { device = "/dev/disk/by-uuid/b96c4d2b-85e4-4ac9-9ef8-aecdcb5f34e8";
      fsType = "btrfs";
      options = [ "subvol=@hdd0" ];
    };

  boot.initrd.luks.devices."crypthdd0".device = "/dev/disk/by-uuid/78615e67-4a20-463a-b800-7fb557dbe532";

  fileSystems."/virt/hdd0" =
    { device = "/dev/disk/by-uuid/f1295a55-6551-4d16-b708-a8425f653f42";
      fsType = "btrfs";
      options = [ "subvol=@whdd0" ];
    };

  boot.initrd.luks.devices."cryptwhdd0".device = "/dev/disk/by-uuid/7c25b0d5-19ce-41ab-94f5-47524bf2aab8";

  fileSystems."/virt/root" =
    { device = "/dev/disk/by-uuid/00eb94ab-a20a-4e5b-807d-b6ab3b23c406";
      fsType = "btrfs";
      options = [ "subvol=@wroot" ];
    };

  boot.initrd.luks.devices."cryptwroot".device = "/dev/disk/by-uuid/5cd6f86b-dca7-4869-9bfc-89748894a704";

  fileSystems."/mnt/hdd1" =
    { device = "/dev/disk/by-uuid/87a589d3-5eb4-4600-a513-6a7d8647f57f";
      fsType = "btrfs";
      options = [ "subvol=@hdd1" ];
    };

  boot.initrd.luks.devices."crypthdd1".device = "/dev/disk/by-uuid/ad0e368a-3910-4d1f-b39b-65a11a69b256";

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
}
