# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/16d112dd-d49b-4de9-9ced-c61fbcc7f5f8";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9ed6dbc5-a3c6-4779-b76a-b729b98ca22f";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/16d112dd-d49b-4de9-9ced-c61fbcc7f5f8";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/16d112dd-d49b-4de9-9ced-c61fbcc7f5f8";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/mnt/ssd0" =
    { device = "/dev/disk/by-uuid/04de61ee-4a5f-4b1c-9970-fadd55304321";
      fsType = "btrfs";
      options = [ "subvol=@ssd0" ];
    };

  boot.initrd.luks.devices."cryptssd0".device = "/dev/disk/by-uuid/c666a8da-56b9-4a89-addb-c3f53f66ff5e";

  fileSystems."/mnt/ssd1" =
    { device = "/dev/disk/by-uuid/36f64ba0-9921-4a79-ab19-e202129edb15";
      fsType = "btrfs";
      options = [ "subvol=@ssd1" ];
    };

  boot.initrd.luks.devices."cryptssd1".device = "/dev/disk/by-uuid/a13588b2-6bee-4f92-9838-456dc5b5ee64";

  fileSystems."/virt" =
    { device = "/dev/disk/by-uuid/cbad62d3-0ccf-402d-a049-888f2f06188e";
      fsType = "btrfs";
      options = [ "subvol=@virt" ];
    };

  boot.initrd.luks.devices."cryptvirt".device = "/dev/disk/by-uuid/78a0f874-6490-4861-992c-39861c2a0017";

  fileSystems."/mnt/hdd0" =
    { device = "/dev/disk/by-uuid/74386bd2-ee2e-4628-a914-4c09decf5c9f";
      fsType = "btrfs";
      options = [ "subvol=@hdd0" ];
    };

  boot.initrd.luks.devices."crypthdd0".device = "/dev/disk/by-uuid/0bd2555f-125b-44a4-a277-ed9cc3da961a";

  fileSystems."/mnt/hdd1" =
    { device = "/dev/disk/by-uuid/27129f83-cefd-423c-bb61-14a6fcc3f853";
      fsType = "btrfs";
      options = [ "subvol=@hdd1" ];
    };

  boot.initrd.luks.devices."crypthdd1".device = "/dev/disk/by-uuid/fbf9337e-becb-434a-aae5-3b68370cc707";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1eb4f3c1-1e97-4ee3-a36c-03039318f214";
      fsType = "btrfs";
      options = [ "subvol=@boot" ];
    };

  boot.initrd.luks.devices."cryptboot".device = "/dev/disk/by-uuid/118a6645-a82e-4600-b5b3-ad6b8b1f1563";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/A46A-55C8";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/21d1dbe1-9c9f-44b0-bf9a-b22b9d05dc02"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
}
